### ISSUE TITLE
is there any suggestions for heatmap ?

### ISSUE THREAD

**Issue by AliMedVisionTech** [tiangexiang/BiO-Net#3]
Thanks for your wonderful work. i shall be very thankful to you if you shared your heatmap.py file or guide me in this case.

**Comment by tiangexiang** [comment]
Hi, by 'heatmaps' do you mean the predicted segmentation masks? If so, they can be easily obtained by changing line 120 (train.py) to 'result = model.predict(x,batch_size=args.batch_size)', and then handle the result varaible as a list of predicted segmentation masks (rather than the evaluation metrics). I will update the code regarding of this issue later this month. Thanks!

**Comment by AliMedVisionTech** [comment]
thanks for your reply, please when you update the code must inform me

**Comment by AliMedVisionTech** [comment]
thank you for you modifications

i have change the line of 46 " x_train, y_train, batch_size=args.batch_size" with " x_train, y_train, batch_size=args.batch" and then also make modification in line 120 "result = model.evaluate(x,batch_size=args.batch)" but i am getting the namespace error. Yes i want to get the predicted Segmentation masks.



Would you like to please give me your wechat mine is (ALISoft005696)
